queue_rules:
  - name: default
    queue_conditions:
      - "-merged"
      - "#approved-reviews-by>=1"
      - base=main
      - label=AUTOMERGE-REQUESTED
      - status-success=Docs
      - status-success=Lint
      - status-success=Python (3.9, macos-latest)
      - status-success=Python (3.13, macos-latest)
      - status-success=Python (3.9, ubuntu-24.04)
      - status-success=Python (3.13, ubuntu-24.04)
      - status-success=Python (3.9, windows-latest)
      - status-success=Python (3.13, windows-latest)
      - "status-success=ci/circleci: build"
    merge_conditions:
      - "#approved-reviews-by>=1"
      - status-success=Docs
      - status-success=Lint
      - status-success=Python (3.9, macos-latest)
      - status-success=Python (3.13, macos-latest)
      - status-success=Python (3.9, ubuntu-24.04)
      - status-success=Python (3.13, ubuntu-24.04)
      - status-success=Python (3.9, windows-latest)
      - status-success=Python (3.13, windows-latest)
      - "status-success=ci/circleci: build"
    merge_method: rebase
    update_method: rebase

pull_request_rules:
  - name: Remove label after merge
    conditions:
      - merged
      - label=AUTOMERGE-REQUESTED
    actions:
      label:
        remove:
          - AUTOMERGE-REQUESTED
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
