queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Docs
      - status-success=Lint
      - status-success=Python (3.7, macos-latest)
      - status-success=Python (3.10, macos-latest)
      - status-success=Python (3.7, ubuntu-latest)
      - status-success=Python (3.10, ubuntu-latest)
      - status-success=Python (3.7, windows-latest)
      - status-success=Python (3.10, windows-latest)
      - "status-success=ci/circleci: build"
pull_request_rules:
  - name: Automatic rebase, CI and merge
    conditions:
      - "-merged"
      - "#approved-reviews-by>=1"
      - base=main
      - label=AUTOMERGE-REQUESTED
      - status-success=Docs
      - status-success=Lint
      - status-success=Python (3.7, macos-latest)
      - status-success=Python (3.10, macos-latest)
      - status-success=Python (3.7, ubuntu-latest)
      - status-success=Python (3.10, ubuntu-latest)
      - status-success=Python (3.7, windows-latest)
      - status-success=Python (3.10, windows-latest)
      - "status-success=ci/circleci: build"
      #- status-success=codecov/patch
      #- status-success=codecov/project/c-tests
      #- status-success=codecov/project/python-c-tests
      #- status-success=codecov/project/python-tests
    actions:
      queue:
        name: default
        method: rebase
        update_method: rebase

  - name: Remove label after merge
    conditions:
      - merged
      - label=AUTOMERGE-REQUESTED
    actions:
      label:
        remove:
          - AUTOMERGE-REQUESTED
