package:
  name: msprime
  version: "0.dev"

source:
  path: ../

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - mspms=msprime.cli:mspms_main
    - msp=msprime.cli:msp_main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1
  string: "py{{CONDA_PY}}_gsl{{CONDA_GSL}}_{{PKG_BUILDNUM}}"

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    # - svgwrite
    - hdf5
    - gsl {{CONDA_GSL}}*

  run:
    - python
    # - svgwrite
    - hdf5
    - numpy
    - h5py
    - gsl {{CONDA_GSL}}*

test:
  # Python imports
  imports:
    - msprime

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - msp --help > /dev/null
    - mspms 2 1 -T > /dev/null

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/msprime
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'A fast and accurate coalescent simulator.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
